[package]
name = "byte_slurper"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1.6"
no-panic = "0.1.15"
num-complex = "0.4.2"

[profile.release]
lto = true
panic = "abort"

[dev-dependencies]
criterion = "0.3"
rand = "0.8"

[[bench]]
name = "payload_to_spectra"
harness = false
