[package]
name = "byte_slurper"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1.6"
no-panic = "0.1.15"
num-complex = "0.4.2"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
