[package]
name = "byte_slurper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.6"
lazy_static = "1.4.0"
rustfft = "6.0.1"
