[package]
name = "byte_slurper"
version = "0.1.0"
edition = "2021"

[dependencies]
af_packet = "0.3"
byte-slice-cast = "1.2"
chrono = "0.4.19"
crossbeam-channel = "0.5"
csv = "1.1"
etherparse = "0.12.0"
no-panic = "0.1"
num-complex = "0.4"
num-traits = "0.2"
psrdada = { git = "https://github.com/GReX-Telescope/psrdada-rs", branch = "main" }

[profile.release]
lto = true
panic = "abort"

[dev-dependencies]
criterion = "0.3"
rand = "0.8"

[[bench]]
name = "payload_to_spectra"
harness = false
